number1=input('Enter number1')
number2=input('Enter number2')
print(number1,number2)
sum=number1+number2
sum=int(number1)+int(number2)
print(sum)
difference=int(number1)-int(number2)
multiplication=int(number1)*int(number2)
division=int(number1)/int(number2)
print(difference,multiplication,division)
number3=input('Enter number3')
sum=int(number1)+int(number2)+int(number3)
difference=int(number1)-int(number2)-int(number3)
multiplication=int(number1)*int(number2)*int(number3)
division=int(number1)/int(number2)/int(number3)
print(sum,difference,multiplication,division)
import math
print(math.pow(9,3))
print(math.tan(45))
print(math.sin(0.00))
print(math.tanh(8))
print(math.sinh(0.00))
print(math.sqrt(9))
print(math.trunc(2.77))
print(math.log2(2))
print(math.cos(1))
print(math.acos(0.1))
